--- 
eu:anub'arak: eu
eu:die silberne hand: eu
cn:bronze dragonflight: cn
cn:illidan: cn
cn:brutallus: cn
cn:well of eternity: cn
eu:hakkar: eu
eu:suramar: eu
cn:mal'ganis: cn
us:suramar: us
cn:dunemaul: cn
cn:spirestone: cn
cn:doomhammer: cn
cn:lothar: cn
us:wyrmrest accord: us
tw:howling fjord: tw
us:eonar: us
cn:khadgar: cn
eu:neptulon: eu
us:shadowmoon: us
us:vashj: us
? !binary "ZXU60JPRgNC+0Lw=\n"
: eu

cn:flame crest: cn
eu:terenas: eu
us:ursin: us
eu:lightning's blade: eu
cn:vek'lor: cn
cn:turalyon: cn
us:terenas: us
us:bonechewer: us
cn:hellscream: cn
us:eldre'thalas: us
us:turalyon: us
us:lightbringer: us
cn:kel'thuzad: cn
cn:frostreaver crown: cn
us:winterhoof: us
cn:cho'gall: cn
cn:splinter fist: cn
eu:azuremyst: eu
us:drak'thul: us
cn:deephome: cn
us:sisters of elune: us
cn:searinox: cn
cn:varimathras: cn
us:thorium brotherhood: us
kr:karazhan: kr
eu:boulderfist: eu
cn:nozdormu: cn
cn:golemagg: cn
cn:staghelm: cn
eu:rashgarroth: eu
cn:sundown marsh: cn
eu:quel'thalas: eu
cn:aerie peak: cn
eu:eredar: eu
eu:ysera: eu
cn:stormrage: cn
eu:bronze dragonflight: eu
cn:zalazane: cn
eu:malorne: eu
kr:al'ar: kr
cn:blood furnace: cn
cn:azshara: cn
us:quel'thalas: us
tw:strand of the ancients: tw
? !binary "ZXU60J/QvtC00LfQtdC80YzQtQ==\n"
: eu

cn:silverpine forest: cn
eu:elune: eu
us:crushridge: us
us:zul'jin: us
eu:drek'thar: eu
cn:anzu: cn
cn:bloodfeather: cn
eu:der abyssische rat: eu
eu:rexxar: eu
eu:lothar: eu
eu:zuluhed: eu
cn:shadowfang keep: cn
cn:hydraxis: cn
us:tanaris: us
eu:al'akir: eu
tw:warsong: tw
us:zuluhed: us
eu:kult der verdammten: eu
cn:drakkisath: cn
us:burning legion: us
us:cenarion circle: us
kr:dalaran: kr
us:dreadmaul: us
us:hydraxis: us
us:silvermoon: us
kr:rexxar: kr
us:korgath: us
kr:aegwynn: kr
cn:thrall: cn
us:arena tournament 1: us
us:agamaggan: us
eu:zirkel des cenarius: eu
cn:bladefist: cn
tw:skywall: tw
eu:frostwhisper: eu
us:arena tournament 2: us
kr:azshara: kr
cn:menethil: cn
us:arena tournament 3: us
cn:bladespire: cn
cn:ironaya: cn
cn:vaelastrasz: cn
cn:nighthaven: cn
? !binary "ZXU60JDQt9GD0YDQtdCz0L7RgQ==\n"
: eu

cn:crushridge: cn
eu:stonemaul: eu
us:arena tournament 4: us
eu:blutkessel: eu
eu:forscherliga: eu
eu:nera'thor: eu
cn:mosh'ogg: cn
us:trollbane: us
? !binary "ZXU60KLQutCw0Ycg0KHQvNC10YDRgtC4\n"
: eu

? !binary "ZXU60JLQtdGH0L3QsNGPINCf0LXRgdC90Y8=\n"
: eu

eu:nathrezim: eu
cn:que'danas: cn
cn:jin'do: cn
cn:tirisfal glades: cn
us:kil'jaeden: us
cn:detheroc: cn
us:muradin: us
cn:ravenholdt: cn
cn:malygos: cn
us:feathermoon: us
cn:andorhal: cn
cn:abyssal maw: cn
cn:river pride: cn
cn:ahn'qiraj: cn
cn:drakkari: cn
cn:darrowmere: cn
eu:naxxramas: eu
eu:laughing skull: eu
cn:dreadmist peak: cn
cn:hectae: cn
cn:ysondre: cn
cn:red cloud mesa: cn
cn:blackwing lair: cn
kr:gul'dan: kr
cn:destromath: cn
cn:kul tiras: cn
eu:alonsus: eu
us:anub'arak: us
cn:arathor: cn
eu:chamber of aspects: eu
eu:shattrath: eu
cn:laughing skull: cn
cn:lich king: cn
cn:ragnaros: cn
tw:arygos: tw
eu:thrall: eu
eu:arena tournament 1: eu
cn:tyr's hand: cn
cn:coilfang: cn
tw:crystalpine stinger: tw
cn:shadow council: cn
eu:aman'thul: eu
tw:deathwing: tw
eu:arena tournament 2: eu
us:ragnaros: us
eu:nazjatar: eu
eu:die todeskrallen: eu
eu:arena tournament 3: eu
cn:tempest keep: cn
eu:stormreaver: eu
cn:dreadmaul: cn
cn:holy chanter: cn
cn:gothik: cn
cn:kil'jaeden: cn
tw:tichondrius: tw
cn:the master's glaive: cn
cn:amani: cn
eu:dalvengyr: eu
eu:arena tournament 4: eu
eu:vek'nilash: eu
us:boulderfist: us
us:garrosh: us
cn:amnennar: cn
us:fenris: us
cn:zealot blade: cn
eu:arena tournament 5: eu
us:bleeding hollow: us
cn:gnomeregan: cn
eu:arena tournament 6: eu
us:gurubashi: us
us:azuremyst: us
eu:gorgonnash: eu
cn:aszune: cn
eu:les sentinelles: eu
cn:agamaggan: cn
? !binary "ZXU60KDQtdCy0YPRidC40Lkg0YTRjNC+0YDQtA==\n"
: eu

cn:shrine of the dormant flame: cn
eu:warsong: eu
eu:balnazzar: eu
us:warsong: us
eu:zul'jin: eu
tw:storm peaks: tw
cn:magtheridon: cn
us:bronzebeard: us
us:nesingwary: us
us:thaurissan: us
eu:frostwolf: eu
eu:los errantes: eu
cn:felmyst: cn
us:gundrak: us
cn:azgalor: cn
us:baelgun: us
cn:bone wastes: cn
eu:tyrande: eu
us:blackwater raiders: us
cn:darkspear: cn
eu:sargeras: eu
cn:gordunni: cn
cn:ashenvale: cn
cn:neptulon: cn
eu:culte de la rive noire: eu
tw:shadowmoon: tw
us:bloodscalp: us
eu:ghostlands: eu
cn:anub'arak: cn
tw:silverwing hold: tw
tw:aeonus: tw
eu:anetheron: eu
cn:anachronos: cn
cn:brann: cn
cn:blue dragonflight: cn
kr:alexstrasza: kr
cn:lightning's blade: cn
us:whisperwind: us
eu:todeswache: eu
us:earthen ring: us
us:area 52: us
cn:taerar: cn
eu:area 52: eu
eu:das konsortium: eu
us:durotan: us
eu:durotan: eu
"eu:confr\xC3\xA9rie du thorium": eu
eu:dragonblight: eu
eu:aszune: eu
eu:eitrigg: eu
us:eitrigg: us
cn:gyth: cn
cn:ravencrest: cn
us:drenden: us
cn:azuregos: cn
us:frostmourne: us
cn:grimtotem: cn
us:stonemaul: us
us:terokkar: us
cn:rajaxx: cn
cn:azjol-nerub: cn
cn:sunstrider: cn
cn:falathim: cn
cn:gurubashi: cn
eu:skullcrusher: eu
eu:chromaggus: eu
eu:steamwheedle cartel: eu
cn:un'goro: cn
us:nathrezim: us
eu:frostmane: eu
eu:kirin tor: eu
eu:kazzak: eu
eu:haomarush: eu
tw:gnomeregan: tw
cn:bloodscalp: cn
cn:demon soul: cn
cn:tanaris: cn
eu:daggerspine: eu
us:gorgonnash: us
eu:kael'thas: eu
cn:ossirian: cn
cn:kurdran: cn
us:thunderlord: us
cn:sapphiron: cn
eu:defias brotherhood: eu
us:blackwing lair: us
eu:dun morogh: eu
cn:wing of the whelping: cn
eu:shen'dralar: eu
us:tortheldrin: us
eu:lordaeron: eu
us:ghostlands: us
us:laughing skull: us
cn:blanchard: cn
cn:dream bough: cn
eu:mannoroth: eu
cn:poison-tipped bone spear: cn
cn:aessina: cn
cn:sylvanas: cn
us:draenor: us
cn:crystalpine stinger: cn
eu:taerar: eu
eu:the venture co: eu
us:ysera: us
cn:zul'aman: cn
cn:arthas: cn
kr:hyjal: kr
cn:deatholme: cn
us:aman'thul: us
cn:archimonde: cn
cn:tichondrius: cn
cn:zul'jin: cn
eu:molten core: eu
cn:c'thun: cn
cn:hogger: cn
us:gorefiend: us
us:dalvengyr: us
cn:arathi: cn
eu:teldrassil: eu
eu:auchindoun: eu
eu:doomhammer: eu
eu:rajaxx: eu
cn:rend: cn
us:alleria: us
cn:blackmoore: cn
cn:medivh: cn
cn:dustwind gulch: cn
eu:twilight's hammer: eu
us:mug'thol: us
eu:blackrock: eu
us:dalaran: us
us:balnazzar: us
eu:kel'thuzad: eu
eu:dalaran: eu
eu:scarshield legion: eu
us:saurfang: us
eu:aegwynn: eu
eu:hellscream: eu
cn:eonar: cn
cn:tarren mill: cn
eu:ulduar: eu
kr:eye of the storm: kr
us:shandris: us
eu:wildhammer: eu
cn:stonemaul: cn
eu:blackhand: eu
us:frostwolf: us
us:arygos: us
us:shadowsong: us
cn:neltharion: cn
kr:arena tournament 1: kr
eu:mug'thol: eu
kr:arena tournament 2: kr
cn:force of elemental: cn
cn:the mechanar: cn
eu:uldum: eu
kr:arena tournament 3: kr
? !binary "ZXU60JPQsNC70LDQutGA0L7QvdC0\n"
: eu

cn:whispering shore: cn
tw:quel'dorei: tw
eu:aerie peak: eu
tw:stormscale: tw
us:vek'nilash: us
us:kargath: us
eu:darkmoon faire: eu
eu:uldaman: eu
eu:eldre'thalas: eu
eu:jaedenar: eu
tw:altar of storms: tw
us:uldaman: us
cn:naxxramas: cn
us:firetree: us
eu:aggramar: eu
cn:scarlet crusade: cn
cn:outland: cn
cn:burning steppes: cn
tw:sundown marsh: tw
us:anetheron: us
cn:jammal'an: cn
cn:galardell: cn
eu:ner'zhul: eu
eu:conseil des ombres: eu
us:uther: us
us:khadgar: us
tw:wintergrasp: tw
eu:medivh: eu
cn:the forgotten coast: cn
cn:lethon: cn
cn:stranglethorn: cn
us:shu'halo: us
cn:gazlowe: cn
tw:world tree: tw
cn:maulgar: cn
cn:shattered halls: cn
cn:gorefiend: cn
tw:nesingwary: tw
cn:dalvengyr: cn
kr:medivh: kr
us:drak'tharon: us
cn:mug'thol: cn
eu:dunemaul: eu
us:windrunner: us
cn:skywall: cn
cn:rangers: cn
eu:der rat von dalaran: eu
cn:prestor: cn
eu:xavius: eu
us:kirin tor: us
us:proudmoore: us
kr:uther: kr
cn:karazhan: cn
us:frostmane: us
cn:thousand needles: cn
cn:argus: cn
us:onyxia: us
eu:colinas pardas: eu
cn:dimensius: cn
us:misha: us
us:garona: us
us:haomarush: us
eu:gilneas: eu
eu:crushridge: eu
cn:balnazzar: cn
tw:nightsong: tw
kr:windrunner: kr
cn:garr: cn
cn:emeriss: cn
cn:modgud: cn
eu:cho'gall: eu
cn:runetotem: cn
cn:entropius: cn
cn:geddon: cn
eu:varimathras: eu
eu:azshara: eu
eu:ravenholdt: eu
kr:zul'jin: kr
cn:emerald dream: cn
us:azshara: us
? !binary "ZXU60K/RgdC10L3QtdCy0YvQuSDQu9C10YE=\n"
: eu

cn:alleria: cn
cn:firegut: cn
cn:astalor: cn
us:mannoroth: us
us:shattered halls: us
eu:bladefist: eu
cn:chillwind point: cn
cn:scholomance: cn
cn:baelgun: cn
cn:durotan: cn
eu:the maelstrom: eu
eu:hyjal: eu
cn:the steamvault: cn
us:chromaggus: us
cn:gorehowl: cn
eu:destromath: eu
cn:windrunner: cn
cn:garithos: cn
cn:ring of trials: cn
us:aerie peak: us
cn:gadgetzan: cn
us:detheroc: us
us:the venture co: us
cn:anetheron: cn
cn:swiftwind: cn
cn:aviana: cn
us:zangarmarsh: us
us:garithos: us
us:akama: us
kr:malfurion: kr
cn:sutarn: cn
cn:theramore: cn
eu:the sha'tar: eu
eu:ahn'qiraj: eu
cn:dustbelcher: cn
eu:burning steppes: eu
tw:menethil: tw
eu:bloodhoof: eu
eu:nordrassil: eu
eu:gul'dan: eu
us:blackrock: us
us:greymane: us
eu:kil'jaeden: eu
us:gul'dan: us
cn:maiev shadowsong: cn
us:drakkari: us
cn:firetree: cn
eu:sanguino: eu
us:magtheridon: us
eu:kul tiras: eu
eu:deathwing: eu
cn:archaedas: cn
cn:xavian: cn
"eu:festung der st\xC3\xBCrme": eu
us:blackhand: us
eu:talnivarr: eu
cn:antonidas: cn
cn:freewind: cn
us:skullcrusher: us
us:coilfang: us
cn:frostmane: cn
cn:stormreaver: cn
cn:northrend: cn
us:ravenholdt: us
eu:khadgar: eu
eu:turalyon: eu
cn:hearthglen: cn
us:auchindoun: us
us:moonrunner: us
eu:ysondre: eu
eu:burning blade: eu
cn:thunder axe fortress: cn
us:doomhammer: us
tw:whisperwind: tw
cn:immol'thar: cn
us:korialstrasz: us
tw:light's hope: tw
cn:thunderaan: cn
cn:valley of kings: cn
cn:executus: cn
us:rexxar: us
eu:theradras: eu
eu:arathor: eu
us:kel'thuzad: us
cn:lordaeron: cn
cn:mossflayer: cn
cn:whisperwind: cn
cn:mannoroth: cn
us:executus: us
eu:azjol-nerub: eu
cn:dreamwalker: cn
cn:draenor: cn
us:borean tundra: us
? !binary "ZXU60JTRgNCw0LrQvtC90L7QvNC+0YA=\n"
: eu

eu:anachronos: eu
us:major league gaming: us
us:azjol-nerub: us
? !binary "ZXU60KLQtdGA0LzQvtGI0YLQtdC/0YHQtdC70Yw=\n"
: eu

kr:norgannon: kr
eu:echsenkessel: eu
cn:altar of storms: cn
us:nazgrel: us
cn:whitemane: cn
eu:ravencrest: eu
eu:darkspear: eu
cn:blackrock: cn
cn:dath'remar: cn
us:argent dawn: us
eu:der mithrilorden: eu
eu:tirion: eu
eu:hellfire: eu
cn:feralas: cn
cn:bloodmaul: cn
us:hakkar: us
cn:the great sea: cn
cn:dun modr: cn
us:lightning's blade: us
eu:sunstrider: eu
cn:jaedenar: cn
cn:thunderlord: cn
cn:blackhand: cn
kr:sartharion: kr
cn:tortheldrin: cn
kr:tirion: kr
us:nordrassil: us
cn:thunderhorn: cn
eu:stormscale: eu
cn:fenris: cn
eu:bloodfeather: eu
cn:death's door: cn
cn:the veiled sea: cn
eu:bloodscalp: eu
cn:grim batol: cn
us:moon guard: us
eu:malfurion: eu
kr:malygos: kr
cn:gul'dan: cn
eu:krag'jin: eu
us:bladefist: us
us:tichondrius: us
cn:danath trollbane: cn
"eu:chants \xC3\xA9ternels": eu
tw:spirestone: tw
us:the forgotten coast: us
cn:silver hand: cn
us:altar of storms: us
eu:nethersturm: eu
cn:khardros: cn
cn:ashbringer: cn
eu:sinstralis: eu
eu:bronzebeard: eu
kr:cenarius: kr
us:barthilas: us
us:uldum: us
eu:genjuros: eu
eu:perenolde: eu
cn:proudmoore: cn
us:eredar: us
eu:moonglade: eu
us:smolderthorn: us
cn:daggerspine: cn
eu:tarren mill: eu
tw:hellscream: tw
cn:circle of blood: cn
eu:ambossar: eu
cn:winterspring: cn
cn:deepfury: cn
cn:al'akir: cn
eu:archimonde: eu
us:lightninghoof: us
us:andorhal: us
us:bloodhoof: us
eu:shattered halls: eu
kr:elune: kr
tw:frenzyheart: tw
cn:frostwhisper: cn
us:maelstrom: us
eu:kor'gall: eu
us:burning blade: us
cn:twisting nether: cn
us:ravencrest: us
cn:ysera: cn
cn:midnight scythe: cn
us:kul tiras: us
us:deathwing: us
us:darrowmere: us
eu:blackmoore: eu
us:lothar: us
us:sentinels: us
cn:molten core: cn
cn:kaleidoscope star: cn
eu:ragnaros: eu
tw:sartharion: tw
eu:die ewige wacht: eu
cn:thunder bluff: cn
cn:the golden plains: cn
eu:kilrogg: eu
us:kilrogg: us
eu:frostmourne: eu
us:madoran: us
cn:sunwell: cn
eu:norgannon: eu
cn:akama: cn
tw:zealot blade: tw
cn:shadowmoon: cn
cn:fist of the titans: cn
? !binary "ZXU60JrQvtGA0L7Qu9GMLdC70LjRhw==\n"
: eu

cn:lushwater oasis: cn
cn:lord kazzak: cn
us:rivendare: us
us:gnomeregan: us
us:shattered hand: us
cn:vancleef: cn
cn:magatha: cn
eu:arak-arahm: eu
tw:chillwind point: tw
cn:guardian blade: cn
cn:stormscale: cn
cn:alterac mountains: cn
cn:rhonin: cn
cn:barthilas: cn
eu:die nachtwache: eu
cn:khaz'goroth: cn
eu:dragonmaw: eu
us:dawnbringer: us
us:scilla: us
eu:les clairvoyants: eu
cn:alexstrasza: cn
cn:anvilmar: cn
eu:sylvanas: eu
us:the scryers: us
us:hyjal: us
"eu:mar\xC3\xA9cage de zangar": eu
eu:nefarian: eu
cn:windshear crag: cn
us:nagrand: us
us:darkspear: us
cn:sinestra: cn
us:anvilmar: us
cn:silvermoon: cn
eu:nagrand: eu
cn:nazjatar: cn
eu:die aldor: eu
cn:maelstrom: cn
eu:das syndikat: eu
us:echo isles: us
us:archimonde: us
kr:blackmoore: kr
cn:duskwood: cn
eu:coliseum 2: eu
us:thrall: us
us:nazjatar: us
cn:deathwing: cn
us:duskwood: us
kr:kargath: kr
us:kalecgos: us
us:llane: us
us:gilneas: us
eu:twisting nether: eu
eu:epitech: eu
us:shadow council: us
kr:stormrage: kr
us:malfurion: us
cn:zuluhed: cn
? !binary "ZXU60KfQtdGA0L3Ri9C5INCo0YDQsNC8\n"
: eu

cn:barrens: cn
eu:terokkar: eu
kr:eonar: kr
cn:bleeding hollow: cn
tw:arthas: tw
us:maiev: us
us:scarlet crusade: us
cn:tyrande: cn
eu:outland: eu
cn:arygos: cn
us:draka: us
cn:theradras: cn
eu:un'goro: eu
us:perenolde: us
us:dark iron: us
cn:sargeras: cn
us:quel'dorei: us
cn:nefarian: cn
us:dentarg: us
cn:rivendare: cn
cn:alythess: cn
cn:the arcatraz: cn
us:stormscale: us
eu:darksorrow: eu
us:aegwynn: us
us:sargeras: us
tw:arena tournament 1: tw
cn:dragonblight: cn
cn:kilrogg: cn
tw:icecrown: tw
us:blade's edge: us
tw:arena tournament 2: tw
eu:grim batol: eu
cn:al'ar: cn
eu:runetotem: eu
tw:arena tournament 3: tw
us:demon soul: us
eu:spinebreaker: eu
cn:mograine: cn
eu:die arguswacht: eu
eu:garrosh: eu
cn:red dragonflight: cn
us:black dragonflight: us
cn:astranaar: cn
us:skywall: us
cn:isillien: cn
cn:skullcrusher: cn
us:jubei'thos: us
tw:dragonmaw: tw
cn:burning blade: cn
cn:dor'danil: cn
eu:sen'jin: eu
eu:eonar: eu
us:sen'jin: us
eu:dentarg: eu
us:illidan: us
cn:boulderfist: cn
us:dethecus: us
eu:vashj: eu
cn:the underbog: cn
tw:wrathbringer: tw
us:farstriders: us
cn:quel'thalas: cn
cn:uldum: cn
cn:murmur: cn
eu:mal'ganis: eu
cn:legion hold: cn
cn:fray island: cn
cn:sethekk: cn
us:norgannon: us
cn:black dragonflight: cn
kr:ragnaros: kr
eu:arygos: eu
eu:saurfang: eu
eu:baelgun: eu
cn:thaurissan: cn
eu:arthas: eu
eu:lightbringer: eu
us:mok'nathal: us
cn:malfurion: cn
eu:dethecus: eu
kr:kul tiras: kr
cn:soulflayer: cn
cn:stratholme: cn
tw:firetree: tw
cn:garona: cn
cn:temple of elune: cn
kr:deathwing: kr
cn:onyxia: cn
cn:bloodhoof: cn
eu:arathi: eu
cn:dark phantom: cn
us:steamwheedle cartel: us
us:dragonmaw: us
kr:burning legion: kr
cn:world tree: cn
cn:perenolde: cn
eu:emerald dream: eu
cn:moonglade: cn
cn:therazane: cn
eu:wrathbringer: eu
cn:warsong: cn
eu:krasus: eu
eu:thunderhorn: eu
cn:icecrown: cn
eu:shadowsong: eu
cn:frostwolf: cn
us:undermine: us
eu:stormrage: eu
cn:liadrin: cn
us:icecrown: us
eu:eu arena pass csbg: eu
eu:nozdormu: eu
cn:madoran: cn
us:wildhammer: us
cn:feathermoon: cn
cn:demon fall canyon: cn
eu:antonidas: eu
kr:llane: kr
? !binary "ZXU60JHQvtGA0LXQudGB0LrQsNGPINGC0YPQvdC00YDQsA==\n"
: eu

cn:dark portal: cn
eu:exodar: eu
eu:mazrigos: eu
cn:abbendis: cn
eu:khaz modan: eu
us:emerald dream: us
eu:madmortem: eu
cn:stromgarde keep: cn
kr:wildhammer: kr
us:kael'thas: us
us:silver hand: us
cn:magmadar: cn
eu:vol'jin: eu
cn:thermaplugg: cn
eu:garona: eu
cn:echo ridge: cn
cn:stonetalon peak: cn
eu:onyxia: eu
cn:eldre'thalas: cn
tw:balnazzar: tw
cn:claw of the shadowmancer: cn
eu:sporeggar: eu
cn:vek'nilash: cn
eu:magtheridon: eu
cn:demonslayer: cn
us:daggerspine: us
kr:garona: kr
cn:hyjal: cn
cn:nekros: cn
us:velen: us
eu:karazhan: eu
cn:gorgonnash: cn
us:alterac mountains: us
cn:gruul: cn
us:coliseum 1: us
cn:smolderthorn: cn
eu:draenor: eu
cn:dar'khan: cn
cn:gold road: cn
kr:durotan: kr
us:stormreaver: us
us:grizzly hills: us
cn:thoradin: cn
eu:c'thun: eu
us:galakrond: us
cn:pandaren: cn
eu:earthen ring: eu
eu:illidan: eu
kr:coliseum 1: kr
us:jaedenar: us
eu:emeriss: eu
? !binary "ZXU60JPQvtGA0LTRg9C90L3QuA==\n"
: eu

? !binary "ZXU60KDQsNC30YPQstC40Lk=\n"
: eu

eu:proudmoore: eu
cn:explorer's league: cn
eu:drak'thul: eu
cn:rexxar: cn
us:runetotem: us
us:blood furnace: us
tw:onyxia: tw
us:arthas: us
cn:ner'zhul: cn
us:elune: us
us:aggramar: us
cn:booty bay: cn
eu:alleria: eu
cn:dragonmaw: cn
eu:temple noir: eu
eu:dun modr: eu
eu:vek'lor: eu
us:ner'zhul: us
us:dath'remar: us
us:dragonblight: us
cn:doomwalker: cn
"tw:kel\xE2\x80\x99thuzad": tw
us:ysondre: us
us:fizzcrank: us
cn:bronzebeard: cn
us:arathor: us
us:caelestrasz: us
us:mal'ganis: us
us:medivh: us
eu:burning legion: eu
eu:malygos: eu
us:malygos: us
tw:black dragonflight: tw
eu:terrordar: eu
us:dunemaul: us
us:the underbog: us
cn:burning legion: cn
cn:dark iron: cn
cn:deathforge: cn
us:malorne: us
us:staghelm: us
cn:eranikus: cn
tw:frostmane: tw
cn:kael'thas: cn
eu:argent dawn: eu
eu:kargath: eu
? !binary "ZXU60KHRgtGA0LDQtiDQodC80LXRgNGC0Lg=\n"
: eu

eu:zenedar: eu
eu:khaz'goroth: eu
? !binary "ZXU60KHQstC10LbQtdCy0LDRgtC10LvRjCDQlNGD0Yg=\n"
: eu

? !binary "ZXU60KHQtdC00L7Qs9GA0LjQsg==\n"
: eu

cn:hakkar: cn
eu:alexstrasza: eu
us:destromath: us
cn:the botanica: cn
cn:cenarius: cn
eu:shattered hand: eu
tw:demon soul: tw
us:exodar: us
tw:bleeding hollow: tw
eu:agamaggan: eu
us:cairne: us
eu:shadowmoon: eu
cn:vilebranch: cn
us:cho'gall: us
us:khaz modan: us
us:thunderhorn: us
us:alexstrasza: us
us:khaz'goroth: us
eu:arena pass 1: eu
us:cenarius: us
tw:coliseum 1: tw
cn:chromaggus: cn
cn:shattered hand: cn
cn:direwing: cn
cn:sen'jin: cn
cn:frostmourne: cn
cn:dentarg: cn
eu:trollbane: eu
"eu:la croisade \xC3\xA9carlate": eu
eu:minahonda: eu
us:stormrage: us
us:spirestone: us
tw:dreadmist peak: tw
cn:fel rock: cn
eu:throk'feroth: eu
cn:aggramar: cn
eu:executus: eu
eu:tichondrius: eu
tw:quel'danas: tw
us:twisting nether: us
tw:demon fall canyon: tw
cn:cassandra: cn
us:azgalor: us
cn:storm eye: cn
cn:greymane: cn
us:hellscream: us
us:spinebreaker: us
cn:itharius: cn
? !binary "ZXU60J/QuNGA0LDRgtGB0LrQsNGPINCx0YPRhdGC0LA=\n"
: eu

us:antonidas: us
eu:silvermoon: eu
us:lethon: us
cn:fire plume ridge: cn
kr:alleria: kr
cn:eredar: cn
cn:firelands: cn
cn:uldaman: cn
kr:hellscream: kr
eu:blade's edge: eu
