development: &DEVELOPMENT
  offline: 0
  version: 45
  guildCap: 200
  region:
    us: United States (US)
    eu: Europe (EU)
    cn: China (CN)
    tw: Taiwan (TW)
    kr: Korea (KR)
  upgrade:
    band: 100
  claim:
    limit: 3  
  pages:
    guild: 25
    ranks: 25
  ranking:
    cap: 250
  group:
    cap: 40
  player:
    maxlevel: 80
    claim: 120 # Minutes
    error: 1 # Hours
    talentpoints: 9
    pvpPercent: 0.60 # Percent of the players equipment that has to be PVP before we consider it a PVP profile
  expiration:
    characters: 1440
    guilds: 1440
    queue: 10
  animations:
    stand: Stand
    laugh: Laugh
    flex: Flex
    chicken: Chicken
    crouch: Crouch
    talk: Talk
    bow: Bow
    rude: Rude
    kiss: Kiss
    point: Point
    salute: Salute
    yes: Yes
    no: No
    train: Train
    readyspelldirected: Casting (targeted)
    castdirected: Casting (general)
    castdirected: Cast (targeted)
    castomni: Cast (general)
  armories:
    - US
    - EU
    - CN
    - TW
    - KR
  reverseFaction:
    alliance: 0
    horde: 1
  faction:
    0: Alliance
    1: Horde
  factionToken:
    0: alliance
    1: horde
  race:
    1: Human
    2: Orc
    3: Dwarf
    4: Night Elf
    5: Undead
    6: Tauren
    7: Gnome
    8: Troll
    10: Blood Elf
    11: Draenei
  raceToken:
    1: human
    2: orc
    3: dwarf
    4: nightelf
    5: undead
    6: tauren
    7: gnome
    8: troll
    10: bloodelf
    11: draenei
  gender:
    0: Male
    1: Female
  class:
    1: Warrior
    2: Paladin
    3: Hunter
    4: Rogue
    5: Priest
    6: Death Knight
    7: Shaman
    8: Mage
    9: Warlock
    11: Druid
  classToken:
    1: warrior
    2: paladin
    3: hunter
    4: rogue
    5: priest
    6: deathknight
    7: shaman
    8: mage
    9: warlock
    11: druid
  reverseClass:
    warrior: 1
    paladin: 2
    hunter: 3
    rogue: 4
    priest: 5
    deathknight: 6
    shaman: 7
    mage: 8
    warlock: 9
    druid: 11
      
test:
  <<: *DEVELOPMENT

production:
  <<: *DEVELOPMENT
